remote_theme: pmarsceill/just-the-docs
logo: /assets/nrel.png
color_scheme: nrel
plugins:
    - jekyll-paginate
    - jekyll-feed
    - jekyll-remote-theme

paginate: 3
paginate_path: /blog/page:num
baseurl: /HPC
search_enabled: true
title: NREL docs
collections:
    announcements:
        output: true