#!/bin/bash
#SBATCH --job-name="4plexos"
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=16
#SBATCH --time=00:15:00
#SBATCH --partition=debug
### You need to change the next line
#SBATCH --account=hpcapps
### You will need change the two lines to point to a directory you own
#SBATCH -o /scratch/kpanda/slurmout/stdout.%j
#SBATCH -e /scratch/kpanda/slurmout/stderr.%j


mkdir $SLURM_JOB_ID
cat $0 > $SLURM_JOB_ID/script
cd $SLURM_JOB_ID

# Next  lines are not required but will force all output to logfile.* including
# slurm stdout and stderr.  To activate/deactivate set to true/false.
if false ; then
exec 3>>logfile.`date +"%y%m%d%H%M%S"`
exec 4>&3
exec 5>&1 6>&2              # save "pointers" to stdin and stdout
exec 1>&3 2>&4              # redirect stdin and stdout to file
fi



export MAX_TEMP_FILE_AGE=50
export PLEXOS_TEMP=`pwd`/plexos_temp
export TEMP=$PLEXOS_TEMP

mkdir -p $PLEXOS_TEMP

## Select our version...

export PLEXOS_VERSION="8.200R01"
export XPRESSMP_VERSION="8.5.6"
export MONO_VERSION="6.8.0.105"

module purge
module load centos mono/$MONO_VERSION xpressmp/$XPRESSMP_VERSION plexos/$PLEXOS_VERSION

# Get our data
wget https://github.nrel.gov/tkaiser2/plexos/raw/master/week.tgz
tar -xzf week.tgz

# What we have
printenv > env
ls -lt
# Make multiple attempts in case we can't get a license
# To simplfy you can take out everything except the "mono"
# line in the for / done block
for attempt in a b c d e ; do
	export WAIT=120
# Time our run
    ./tymer times begining
    mono $PLEXOS/PLEXOS64.exe -n "one_week_model.xml" -m DAY_AHEAD &> mono_log.$SLURM_JOB_ID || echo "mono fail"
    ./tymer times finished
	grep "Unable to acquire license" mono_log.$SLURM_JOB_ID >& /dev/null
	if [ $? -eq 0 ] ; then
		date                              >> ping.out
		ping -c 3 $HOSTNAME               >> ping.out
                ping -c 3 eagle-dav.hpc.nrel.gov  >> ping.out
                ping -c 3 google.com              >> ping.out
                ping -c 3 10.60.3.188             >> ping.out
		cp mono_log.$SLURM_JOB_ID mono_log.$SLURM_JOB_ID.$attempt
		#mail <  mono_log.$SLURM_JOB_ID -s $SLURM_JOB_ID  USER@nrel.gov
		echo will try again in $WAIT seconds
		sleep $WAIT
	else
		echo "found it"
		break
	fi
done

# Remove the files in the *tgz file.  We don't need them anymore.
tar -tzf week.tgz | grep -v tymer |sed "s,/.*,," | sort -u  | while IFS= read -r line ; do rm -rf "$line" ; done

# Copy slurm stderr & stdout to this directory.
# You will need to change the next line to point to the directory specified in the header.
cp /scratch/${USER}/slurmout/std*.$SLURM_JOB_ID . || echo "No std*.$SLURM_JOB_ID"
