#!/usr/bin/env python3

#### copy this file to ~/bin
#### ln -s tymer myutils.py
import sys
import time
import os.path
global doquit
doquit=False

import io 
def sprint(*args, **kwargs): 
	'''Use like print but returns a string instead of printing.'''
	sio = io.StringIO() 
	print(*args, **kwargs, file=sio) 
	return sio.getvalue() 
	 
def pdappend(df,line):
    import pandas as pd
    a_series = pd.Series(line, index = df.columns)   
    return df.append(a_series, ignore_index=True)   

def pdaddrow(indf,inline,dell=" "):
    import pandas as pd
    if type(inline) == str:
        inline=inline.split(dell)
    cols=indf.columns
    if len(cols) != len(inline):
        print("in pdaddrow row length mismatch dataframe = ",len(cols), " input row = ",len(inline))
        print(inline)
        if dell == "\t":
            print("delimiter is tab")
        else:
            print("delimiter is ",dell)
        return indf
    adict={}
    for (h,v) in zip(cols,inline) :
        adict[h]=[v]
    #print(adict)
    inline=pd.DataFrame(adict)
    return(pd.concat([indf,inline],ignore_index = True))
 
 
def rreplace(s, old, new="",count=1):
    return (s[::-1].replace(old[::-1], new [::-1], count))[::-1]


#returns output from the magic command %%capture as a list
def clist(cap):
	'''Returns output from the magic command %%capture as a list'''
	if len(cap._stdout.__getstate__()[0]) > 0:
		return(cap.stdout.split())
	rstr=""
	for i in cap._outputs :
		try:
			s=i['data']['text/plain']
			s=s.replace("\\n","\n")
			s=s.strip("'")
			rstr=rstr+sprint(s)
		except:
			pass
	return(rstr.split())


def greenbar(input,color="green"):
    if input == "help":
        print("Adds a css to a html file, in particular a table")
        print("NORMAL USAGE:")
        print("Assuming we have a dataframe 'bytime'")
        print('tmp=bytime.to_html(index=False)')
        print('tmp=greenbar(tmp,color="blue")')
        print('f=open("top_users.html","w")')
        print('f.write(tmp)')
        print('f.close()')
        return None
    header="""<!DOCTYPE html>
<html lang="en">
<head>    
 <meta charset="utf-8" />
 <title>Untitled</title>
<style>
BODY { background-color: #DDD; }
.greenbar { font-family: "Trebuchet MS", Arial, Helvetica, sans-serif; border-collapse: collapse; width: 100%; }
.greenbar th { font-size: 1.4em; text-align: center; padding-top: 5px; padding-bottom: 4px; background-color: #A7C942; color: #fff; }
.greenbar td { font-size: 1.0em; border: 1px solid #98bf21; text-align: right; padding: 3px 7px 2px 2px; }
.greenbar tr:nth-child(odd) td { color: #000; background-color: #EAF2D3; }
.greenbar tr:nth-child(even) td { color: #000; background-color: #ffffff; }
.greenbar td:nth-child(300n+0) { text-align: left; }
.greenbar td:nth-child(400n+0) { text-align: center; }
.greenbar td:nth-child(500n+0) { text-align: right; }
.bluebar { font-family: "Trebuchet MS", Arial, Helvetica, sans-serif; border-collapse: collapse; width: 100%; }
.bluebar th { font-size: 1.4em; text-align: left; padding-top: 5px; padding-bottom: 4px; background-color: #646490; color: #fff; }
.bluebar td { font-size: 1.0em; border: 1px solid #0000ff; padding: 3px 7px 2px 2px; }
.bluebar tr:nth-child(odd) td { color: #000; background-color: #DCDCFF; }
.bluebar tr:nth-child(even) td { color: #000; background-color: #ffffff; }
.bluebar td:nth-child(300n+0) { text-align: left; }
.bluebar td:nth-child(400n+0) { text-align: center; }
.bluebar td:nth-child(500n+0) { text-align: right; }
.narrow { width: 25%; text-align: center; }
</style>
<table class="bluebar">  
"""
    if color== "green" :
        header=header.replace('class="bluebar"','class="greenbar"')
    tail="""</body>
</html>
"""
    tmp=input.replace('<table border="1" class="dataframe">',"")

    return header+tmp+tail


def tymer(sys_argv=""):
	'''nice timer. For help tymer("-h")'''

	secs=time.time()
	date=time.asctime()
	delta=0
	delta2=0
	comment=""
	file=""
	if doquit==False:
		if isinstance(sys_argv,list):
			sys_argv=["dummy"]+sys_argv
		else:
			sys_argv=["dummy"]+[sys_argv]
	if len(sys_argv) > 2:
		for x in sys_argv[2:]:
			comment=comment+x+" "
		comment=comment.strip()

	if len(sys_argv) > 1:
		file=sys_argv[1]
	else:
		s="%17.6f %s %10.3f" % (secs,date,delta)
		print(s)
		if doquit:
			quit()
	if len(file) == 0:
		s="%17.6f %s %10.3f" % (secs,date,delta)
		print(s+" "+comment)
		return(None)		
	if file == "-h" or file == "-help" or file == "--h" :
		print("")
		print("USAGE:")
		print("")
		print(sys_argv[0]," [file] [comment]")
		print("")
		print("With no input on the command line prints")
		print("time in seconds and date to the screen.")
		print("")
		print("With a file name on the command line it reads")
		print("the file, if it exists, and prints a delta time")
		print("from the last time this program updated the file")
		print("and appends the time information to the file.")
		print("")
		print("Note: file can be /dev/null or \"\"")
		print("")
		print("If the file does not exist it creates it and")
		print("write the current time information.")
		print("You can add optional comments that will be added")
		print("to the end of the line.")
		s="%17.6f %s %10.3f %10.3f" % (secs,date,delta,delta2)
		print("")
		print("tymer can be called as a function:")
		print("from tymer import *")
		print('tymer()							prints to stdout')						
		print('tymer("file")					prints to file')
		print('tymer("-i")						use an internal file for saving time')
		print('tymer(["file","comments"])		prints to file with comments')
		print('tymer(["","comments"])			prints to stdout with comments')
		print('tymer(["/dev/null","comments"])	prints to stdout with comments')
		print("")
		print(s)
		if doquit : 
			quit()	
	
	if(file == "-i"):
		lines=tymer_save.getvalue()
		if len(lines) > 0 :
			lines=lines.split("\n")
			lines.reverse()
			if(len(lines[0]) == 0): lines=lines[1:]
	# calculate a delta
			ll=lines[-1]
			try:
				last=ll.split()
				pre=float(last[0])
			except:
				pre=secs
			ll=lines[0]
			try:
				last=ll.split()
				post=float(last[0])
			except:
				post=secs
		else:
			pre=secs
			post=secs		
		delta=secs-pre
		delta2=secs-post
	# print secs,date,delta
		s="%17.6f %s %10.3f %10.3f %s" % (secs,date,delta,delta2,comment)
		print(s)
		tymer_save.write(s+"\n")
		return(None)		
	
	#two cases
	exists=os.path.exists(file)
	# file exists
	if exists :
	# open it for read
		with open(file, "r") as myfile:
			lines=myfile.readlines()
	# close it
			myfile.close()
	# get the last line
		if len(lines) > 0 :
	# calculate a delta
			ll=lines[-1]
			try:
				last=ll.split()
				pre=float(last[0])
			except:
				pre=secs
			ll=lines[0]
			try:
				last=ll.split()
				post=float(last[0])
			except:
				post=secs
		else:
			pre=secs
			post=secs
		
		delta=secs-pre
		delta2=secs-post
	# print secs,date,delta
		s="%17.6f %s %10.3f %10.3f %s" % (secs,date,delta,delta2,comment)
		print(s)
		with open(file, "a") as myfile:
			myfile.write(s+"\n")
			myfile.close()
		if doquit : 
			quit()

	# file does not exist
	else:
		s="%17.6f %s %10.3f %10.3f %s" % (secs,date,delta,delta2,comment)
		print(s)
	#open it
		with open(file, "w") as myfile:
			myfile.write(s+"\n")
			myfile.close()
		if doquit : 
			quit()
if __name__ == '__main__':
	doquit=True
	tymer(sys.argv)
else:
	from io import StringIO
	tymer_save = StringIO()


	
