FILE_TO_DOWNLOAD=$1
HPC_USERNAME=$2
NREL_CLUSTER=$3
REMOTE_LOCATION=$4
rsync -chavzP --no-g \
	${HPC_USERNAME}@${NREL_CLUSTER}.hpc.nrel.gov:${REMOTE_LOCATION}/${FILE_TO_DOWNLOAD} \
	./${FILE_TO_DOWNLOAD}

