#!/bin/bash
#SBATCH --time=0:30:00
#SBATCH --partition=gpu-h100
#SBATCH --nodes=2
#SBATCH --gres=gpu:h100:4
#SBATCH --exclusive
#SBATCH --output=output-%j.out
#SBATCH --error=infor-%j.out

# a simple timer
dt ()
{
    now=`date +"%s.%N"`;
    if (( $# > 0 )); then
        rtn=$(printf "%0.3f" `echo $now - $1 | bc`);
    else
        rtn=$(printf "%0.3f" `echo $now`);
    fi;
    echo $rtn
}

startdir=`pwd`
doits=`find . -name doit`
for x in $doits ; do
	echo found example in `dirname $x`
done
t1=`dt`
for x in $doits ; do
 dir=`dirname $x`
 echo ++++++++ $dir >&2 
 echo ++++++++
 echo $dir
 cd $dir
 tbegin=`dt`
 . doit
 echo Runtime `dt $tbegin` $dir `dt $t1` total
 cd $startdir
done
echo FINISHED `dt $t1`

